version: '2'
services:
  spring_cloud_eureka:
    image: cielqian/spring_cloud_single_eureka
    hostname: eureka
    container_name: spring_cloud_eureka
    ports:
      - '9001:9001'
    networks: 
      - 'front-tier'
  spring_cloud_producer_peer1:
    image: cielqian/spring_cloud_producer
    container_name: spring_cloud_producer_peer1
    ports:
      - '9012:9011'
    links: 
      - spring_cloud_eureka
    networks: 
      - 'front-tier'
  spring_cloud_producer_peer2:
    image: cielqian/spring_cloud_producer
    container_name: spring_cloud_producer_peer2
    ports:
      - '9013:9011'
    depends_on:
      - spring_cloud_eureka
    links: 
      - spring_cloud_eureka
networks:
  front-tier:
    driver: bridge
