server:
  port: 9001

spring:
  application:
    name: spring-cloud-eureka
  profiles:
    active: peer1

peer1:
  port: 8001
peer2:
  port: 8002

---
spring:
  profiles: peer1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eurekapeer2:${peer2.port}/eureka/
  instance:
    hostname: eurekapeer1

---
spring:
  profiles: peer2
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eurekapeer1:${peer1.port}/eureka/
  instance:
    hostname: eurekapeer2