config:
  eureka:
    defaultZone:  http://10.80.29.106:9001/eureka/
spring:
  application:
    name: spring-cloud-api-gateway
server:
  port: 9050
eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.defaultZone}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}