server:
  port: 9042
spring:
  application:
    name: spring-cloud-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  cloud:
    bus:
      trace:
        enabled: true
management:
  security:
    enabled: false
