server:
  port: 9041
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cielqian/spring-cloud-examples/
          search-paths: config-repo
          username: qianhong91@outlook.com
          password: asd5215062
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.80.26.71:9001/eureka/
management:
  security:
    enabled: false