config:
  eureka:
    defaultZone:  http://10.80.29.106:9001/eureka/

spring:
  application:
    name: spring-cloud-eureka
server:
  port: 9001
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${config.eureka.defaultZone}
  instance:
    hostname: eureka
    prefer-ip-address: true

