config:
  eureka:
    defaultZone:  http://10.80.29.106:9001/eureka/
server:
  port: 9060
spring:
  application:
    name: spring-cloud-zipkin-server
eureka:
  client:
    service-url:
      defaultZone: ${config.eureka.defaultZone}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true