config:
  eureka:
    defaultZone:  http://10.80.29.106:9001/eureka/
  rabbitmq:
    host: 10.80.29.106
  zipkin:
    baseUrl: http://10.80.29.106:9060/
spring:
  application:
    name: spring-cloud-producer
  rabbitmq:
    host: ${config.rabbitmq.host}
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
  zipkin:
    base-url: ${config.zipkin.baseUrl}
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.defaultZone}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}