spring:
  application:
    name: spring-cloud-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.80.26.71:9001/eureka/